version: "3"
services:
  hapi-fhir-postgres:
    image: postgres:13-alpine
    container_name: postgres-hapi-fhir
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  hapi-fhir-postgres:
